name: Publish

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Test", "Lint"]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push')
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ sinsir2 }}
          password: ${{ secret.token }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./stations
          push: true
          tags: |
            ${{ sinsir2 }}/mqtt-weather-station:latest
            ${{ sinsir2 }}/mqtt-weather-station:${{ github.sha }}
